### ISSUE TITLE
build error after upgrade from 8.9 to 9.11

### ISSUE THREAD

**Issue by amirzaeii** [bitfoundation/bitplatform#11164]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

recently after upgrading my project from version 8.9 to 9.11 my project build has following error:

**error CS0246: The type or namespace name 'AppQueryStringCollection' could not be found (are you missing a using directive or an assembly reference?)**

what do you think?what is the problem or what do I do?
thank you

### Expected Behavior

successfully build

### .NET Version

9.0.303

**Comment by ysmoradi** [comment]
I asked the exact question from [our wiki](https://wiki.bitplatform.dev/search/recently-after-upgrading-my-pr_215df7d3-2c2a-49ba-aba8-826ce1e25ce2). Check if it helps or not and let us know.

**Comment by ysmoradi** [comment]
> I asked the exact question from [our wiki](https://wiki.bitplatform.dev/search/recently-after-upgrading-my-pr_215df7d3-2c2a-49ba-aba8-826ce1e25ce2). Check if it helps or not and let us know.

@amirzaeii Did you check this?!
